backend:
  name: github
  repo: pointy-secrets/whispering
  branch: main
  # Make sure this URL is correct and has NO trailing slash
  auth_endpoint: https://grass-labrynth-auth.yip-3e3.workers.dev

media_folder: "assets/music"
public_folder: "/assets/music"

collections:
  - name: "songs"
    label: "Songs"
    folder: "_data/songs"
    create: true
    fields:
      - { label: "Track Name (What)", name: "name", widget: "string" }
      - { label: "User (Who)", name: "user", widget: "string" }
      - { label: "Audio File", name: "audio", widget: "file", media_types: ["audio/mpeg"] }   
